### PR TITLE
Add Firefox support

### PR DESCRIPTION
**Pull request by marcii**
Firefox support is possible with the new WebExtensions model.

The `chrome-extension` URL scheme isn't supported (Firefox uses `moz-extension`), and local URLs don't work for content-script CSS, so this just does it dynamically from the content script.

### CODE REVIEW

**Comment by tom-james-watson** [comment]
Hey @marcii - this is awesome! I hadn't realised Firefox had introduced support for WebExtensions. Really cool.

I've merged and and have sent the app to the addon store for review. I'll let you know when it's accepted.

Many thanks!

**Comment by tom-james-watson** [comment]
ah @marcii - I'm wondering whether you have also submitted it to the the addon store as the slug "reddit-comment-collapser" was not available. 

If you have, do you mind closing that submission and we'll make my one the official one.

It will be easier if I am the one that manages all releases. Thanks!

**Comment by marcii** [comment]
Oh, don't worry. That's probably an old port I submitted years ago. Don't think it ever passed review.

**Comment by tom-james-watson** [comment]
https://addons.mozilla.org/en-GB/firefox/addon/reddit_comment_collapser/

**Pull request merged**
